# Generated by Django 5.0.6 on 2024-06-04 09:40

import datetime
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='image/', verbose_name='Image')),
                ('email', models.EmailField(blank=True, default='rosha.thailand@gmail.com', max_length=254, null=True)),
                ('concert_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('deadline', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('announcement_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('description_payment', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
